import User from '../models/User.js';
import Company from '../models/Company.js';
import sendEmail from '../utils/sendEmail.js';
import crypto from 'crypto';
import { decrypt } from '../utils/encryption.js';
import { createActivityLog } from '../utils/logger.js';

export const createUser = async (req, res, next) => {
  try {
    const { name, email, role, designation, department } = req.body;
    let { password } = req.body;

    // 0) Fetch Company SMTP Config and Validate
    const company = await Company.findById(req.user.companyId).select('+smtpConfig.pass');
    if (!company || !company.smtpConfig || !company.smtpConfig.host || !company.smtpConfig.user || !company.smtpConfig.pass) {
        return res.status(400).json({ 
            status: 'fail', 
            message: 'Company Email (SMTP) not configured. Please setup your email settings in the Settings page before adding members.' 
        });
    }

    // Generate a temporary password if none provided
    const isAutoGenerated = !password;
    if (isAutoGenerated) {
        password = crypto.randomBytes(4).toString('hex'); // 8 character random string
    }
    
    // Ensure the new user belongs to the same company as the admin
    const newUser = await User.create({
      name: name || email.split('@')[0],
      email,
      password,
      role,
      designation,
      department,
      companyId: req.user.companyId,
      profilePic: req.file ? req.file.path : undefined,
      mustChangePassword: true, // Force new users to change password
    });

    // Send Onboarding Email
    try {
        const setupLink = `${process.env.FRONTEND_URL || 'http://localhost:5173'}/setup-password?email=${email}`;
        
        // Decrypt SMTP Password for sending
        const decryptedSmtpPass = decrypt(company.smtpConfig.pass);

        const html = `
            <div style="font-family: Arial, sans-serif; max-width: 600px; margin: auto; padding: 20px; border: 1px solid #eee; border-radius: 10px;">
                <h2 style="color: #333;">Welcome to Work Management!</h2>
                <p>Hello <strong>${name || email.split('@')[0]}</strong>,</p>
                <p>Your account has been created by your administrator. Please use the following credentials to set up your permanent password:</p>
                <div style="background: #f4f4f4; padding: 15px; border-radius: 5px; margin: 20px 0;">
                    <p style="margin: 5px 0;"><strong>Email:</strong> ${email}</p>
                    <p style="margin: 5px 0;"><strong>Temporary Password:</strong> ${password}</p>
                </div>
                <p>Click the button below to complete your registration:</p>
                <a href="${setupLink}" style="display: inline-block; padding: 12px 24px; background-color: #ea580c; color: #fff; text-decoration: none; border-radius: 5px; font-weight: bold;">Setup Your Password</a>
                <p style="margin-top: 30px; font-size: 12px; color: #888;">If the link doesn't work, copy and paste this into your browser: <br/> ${setupLink}</p>
            </div>
        `;

        // Convert Mongoose subdoc to plain object to avoid spread issues
        const smtpConfigPlain = company.smtpConfig ? company.smtpConfig.toObject() : null;

        await sendEmail({
            email,
            subject: 'System Onboarding: Your New Account',
            message: `Welcome! Your temp password is: ${password}. Setup here: ${setupLink}`,
            html: html,
            smtpConfig: smtpConfigPlain ? {
                ...smtpConfigPlain,
                pass: decryptedSmtpPass
            } : null
        });
    } catch (emailErr) {
        console.error('Onboarding email failed:', emailErr);
        // We don't fail the user creation if email fails, but we log it.
        // In a real app, you might want a "Resend Invitation" button.
    }

    // Remove password from output
    newUser.password = undefined;

    res.status(201).json({
      status: 'success',
      data: {
        user: newUser,
      },
    });

    createActivityLog(req, {
      action: 'Create Member',
      module: 'Team',
      description: `Created new team member: ${newUser.name} with role ${newUser.role}`
    });
  } catch (err) {
    if (err.code === 11000) {
      return res.status(400).json({ message: 'Email already exists' });
    }
    res.status(400).json({ status: 'fail', message: err.message });
  }
};

export const getAllUsersByCompany = async (req, res, next) => {
  try {
    const { page = 1, limit = 8 } = req.query;
    const companyId = req.user.companyId;

    const skip = (parseInt(page) - 1) * parseInt(limit);

    const [users, totalUsers] = await Promise.all([
      User.find({ companyId })
        .skip(skip)
        .limit(parseInt(limit))
        .select('-password')
        .lean(),
      User.countDocuments({ companyId })
    ]);

    res.status(200).json({
      status: 'success',
      pagination: {
        totalUsers,
        totalPages: Math.ceil(totalUsers / limit),
        currentPage: parseInt(page)
      },
      data: { users },
    });
  } catch (err) {
    next(err);
  }
};

export const updateUser = async (req, res, next) => {
  try {
    const { name, role, email, password, designation, department } = req.body;
    
    // Find the user first
    const user = await User.findOne({ _id: req.params.id, companyId: req.user.companyId });

    if (!user) {
      return res.status(404).json({ status: 'fail', message: 'User not found in your company' });
    }

    // Update fields
    if (name) user.name = name;
    if (role) user.role = role;
    if (email) user.email = email;
    if (password) user.password = password; // pre-save hook will hash this
    if (designation !== undefined) user.designation = designation;
    if (department !== undefined) user.department = department;
    if (req.file) user.profilePic = req.file.path;

    await user.save();

    // Remove password from output
    user.password = undefined;

    res.status(200).json({
      status: 'success',
      data: { user },
    });

    createActivityLog(req, {
      action: 'Update Member',
      module: 'Team',
      description: `Updated member details for ${user.name}`
    });
  } catch (err) {
    if (err.code === 11000) {
      return res.status(400).json({ message: 'Email already exists' });
    }
    res.status(400).json({ status: 'fail', message: err.message });
  }
};

export const deleteUser = async (req, res, next) => {
  try {
    // Ensure the user being deleted belongs to the admin's company
    const user = await User.findOneAndDelete({
      _id: req.params.id,
      companyId: req.user.companyId
    });

    if (!user) {
      return res.status(404).json({ status: 'fail', message: 'User not found in your company' });
    }

    res.status(204).json({
      status: 'success',
      data: null,
    });

    createActivityLog(req, {
      action: 'Delete Member',
      module: 'Team',
      description: `Deleted team member: ${user.name}`
    });
  } catch (err) {
    next(err);
  }
};
